### ISSUE TITLE
Multiple lasso

### ISSUE THREAD

**Issue by whatwehaveunlearned** [skokenes/D3-Lasso-Plugin#1]
Hi, 

First of all thanks for this awesome plugin. 

I write this in order to say that I would like to have various graphs with a lasso in each one and manage the selections. I have not been able to make this work and I haven't seen any option or mention of this. I am looking at the plugin code now. I am thinking on coding something in order to do this if I see that is not possible. I would appreciate some help or maybe is a very simple issue and you can explain me how to do it.

Thanks!

**Comment by skokenes** [comment]
Hi, I see you closed this. Does that mean you solved the issue?

You should be able to instantiate multiple lassos on a page, like

var myLasso1 = d3.lasso();

var myLasso2 = d3.lasso();

You could use them for separate graphs that way; they will just need to have different areas assigned to keep them separate during the lasso interaction.

**Comment by whatwehaveunlearned** [comment]
Hi thank you for the rapid response! :) I closed it because I thought I post it too fast and maybe it was not and  issue and is just that I didn´t know how to do it. I still haven´t been able to make it work though. My setup is a bit different. I have extracted the lasso to be a function outside the graph. 

function lassoFunction(svg) and I return the lasso. I pass the svg in order to keep the areas asigned different.

I have another function that paints scatterplot charts inside it a variable called lasso = lassoFunction(svg) this one passes the svg in which is rendering. 

I create 2 graphs rendering in 2 different svgs. The first one the lasso works perfectly. The second one the lasso runs and paints but does not enter somehow the lasso_draw function it never runs jumps from lasso_start and when you finish the selection to lasso_end, so the d.possible does not get assigned. lasso_start and lasso_end work perfectly. You have any idea why this might be happening?

**Comment by skokenes** [comment]
Would it be possible for you to post some example code for me to look at?
Thanks

**Comment by whatwehaveunlearned** [comment]
Sure!

I attach both functions lassoFunction creates the lasso and function scatterplot creates a scatterplot and calls the lassoFunction. I create two scatterplots using this function.

The actual code is here: https://github.com/whatwehaveunlearned/visualizator

I am just thinking about solutions so I have no documentation sorry for that, but in case you want to try it launch browse to main.html do a lasso in the graph click the selection and click add in the menu this should create another scatterplot and you can see what is happening...

Thank you so much! :)

function lassoFunction (svg,color){
  // Lasso functions to execute while lassoing
  var lasso_start = function() {
    lasso.items()
      //.attr("r",3.5) // reset size
      .style("fill",null) // clear all of the fills
      .classed({"not_possible":true,"selected":false}); // style as not possible
  };

  var lasso_draw = function() {
    // Style the possible dots
    lasso.items().filter(function(d) {return d.possible===true})
      .classed({"not_possible":false,"possible":true});

```
// Style the not possible dot
lasso.items().filter(function(d) {return d.possible===false})
  .classed({"not_possible":true,"possible":false});
```

  };

  var lasso_end = function() {

```
var selected;
// Reset the color of all dots
lasso.items()
   .style("fill", function(d) { return color(d.species); });

// Style the selected dots
selected=lasso.items().filter(function(d) {
  console.log("s");
  return d.selected===true})
  .classed({"not_possible":false,"possible":false})
  .attr("r",17)
  .on("click",function(d){
    menu(d3.mouse(this),svg);  
  });

// Reset the style of the not selected dots
lasso.items().filter(function(d) {return d.selected===false})
  .classed({"not_possible":false,"possible":false})
  //.attr("r",3.5);

  for (i=0; i<selected[0].length;i++) {
    selectedItems.push(db[selected[0][i].id.split("_")[1]])
  }

//Remove duplicates from selectedItems
removeDuplicates(selectedItems);
```

  };

  // Create the area where the lasso event can be triggered
  var lasso_area = svg.append("rect")
                        .attr("width",width)
                        .attr("height",height)
                        .style("opacity",0);

  // Define the lasso
  var lasso = d3.lasso()
        .closePathDistance(75) // max distance for the lasso loop to be closed
        .closePathSelect(true) // can items be selected by closing the path?
        .hoverSelect(true) // can items by selected by hovering over them?
        .area(lasso_area) // area where the lasso can be started
        .on("start",lasso_start) // lasso start function
        .on("draw",lasso_draw) // lasso draw function
        .on("end",lasso_end); // lasso end function

  // Init the lasso on the svg:g that contains the dots
  svg.call(lasso);

  return lasso;
}

function scatterPlot(){

  graphCounter = graphCounter +1;
  areaCreator(graphCounter);

  var x = d3.scale.linear()
      .range([0, width]);

  var y = d3.scale.linear()
      .range([height, 0]);

  var color = d3.scale.category10();

  var xAxis = d3.svg.axis()
      .scale(x)
      .orient("bottom");

  var yAxis = d3.svg.axis()
      .scale(y)
      .orient("left");

  var svg = d3.select("#graphArea"+graphCounter).append("svg")
      .attr("width", width + margin.left + margin.right)
      .attr("height", height + margin.top + margin.bottom)
    .append("g")
      .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

  //Call lasso function
  var lasso = lassoFunction(svg,color);
  //lassoArray.push[lasso];

```
x.domain(d3.extent(dataset, function(d) { return d[0]; })).nice();
y.domain(d3.extent(dataset, function(d) { return d[1]; })).nice();

svg.append("g")
    .attr("class", "x axis")
    .attr("transform", "translate(0," + height + ")")
    .call(xAxis)
  .append("text")
    .attr("class", "label")
    .attr("x", width)
    .attr("y", -6)
    .style("text-anchor", "end")
    .text(plot.xAxis);

svg.append("g")
    .attr("class", "y axis")
    .call(yAxis)
  .append("text")
    .attr("class", "label")
    .attr("transform", "rotate(-90)")
    .attr("y", 6)
    .attr("dy", ".71em")
    .style("text-anchor", "end")
    .text(plot.yAxis)

svg.selectAll(".dot")
    .data(dataset)
  .enter().append("circle")
    .attr("id",function(d,i) {return "dot_" + i;}) // added
    .attr("class", "dot"+graphCounter)
    .attr("r", 3.5)
    .attr("cx", function(d) { return x(d[0]); })
    .attr("cy", function(d) { return y(d[1]); })
    .style("fill", function(d) { return color(d.species); });

lasso.items(d3.selectAll(".dot"+graphCounter));

var legend = svg.selectAll(".legend")
    .data(color.domain())
  .enter().append("g")
    .attr("class", "legend")
    .attr("transform", function(d, i) { return "translate(0," + i * 20 + ")"; });

legend.append("rect")
    .attr("x", width - 18)
    .attr("width", 18)
    .attr("height", 18)
    .style("fill", color);

legend.append("text")
    .attr("x", width - 24)
    .attr("y", 9)
    .attr("dy", ".35em")
    .style("text-anchor", "end")
    .text(function(d) { return d; });

title(svg);
```

}

**Comment by whatwehaveunlearned** [comment]
I am getting an error on this line on the ondraw function. in lasso.js

Cannot read property 'value' of undefined
var complete_path_d = d3.select("path")[0][0].attributes.d.value + "Z";

**Comment by whatwehaveunlearned** [comment]
have you been able to take a look at it? I had not been able to fix the issue.

**Comment by skokenes** [comment]
Hi,

I am going to take a look at it this weekend. Thanks

Speros

**Comment by whatwehaveunlearned** [comment]
No, thank you! :)

**Comment by skokenes** [comment]
Hey, just an update - I am still looking into this. 

Thanks

Speros

**Comment by whatwehaveunlearned** [comment]
How is it going? now way to find the issue?

thank you

**Comment by skokenes** [comment]
Hey, I think I have fixed the issue. Can you pull down the latest version of lasso.js and try it?

Thanks

Speros

**Comment by whatwehaveunlearned** [comment]
O my God! Im so happy! It works!!! Hehe. Let me give it a little bit more testing in a few hours but it looks like it works!! Thank you so much! 

Another thing i have been thinking about is have you tested the lasso in a scatterplot of a lot of dots say 10-50000 points. I tried it and I think it can not handle it. But maybe it was part of my code. Even though I imagine looking at the code that the scalability is difficult because you have to track all the points of the graph at the same time. what do you think?

Again thank you so much for your time! :)

**Comment by skokenes** [comment]
I'd anticipate poor performance with that many items. Every time you drag the lasso, it re-checks every single item to see if it is inside the lasso or not. This check involves several conditional statements that are evaluated. With a lot of items, I think those operations would add up and slow things down.

**Comment by whatwehaveunlearned** [comment]
I won’t look at the issue for now. But probably in the near future I will need to address the issue of creating the selection in a way where it is feasible to scale for so many points. I think one way is checking less times during the drag. Even though your selection will not be so accurate but it could do the trick. It would be interesting for you to make it scalable for so many points? 

Alberto González Martínez
whatwehaveunlearned@gmail.com

**Comment by FabianColque** [comment]
Thanks Skokenes for update it, I had the same problem.
