### ISSUE TITLE
Lasso not selecting all points in selection

### ISSUE THREAD

**Issue by projecttiles** [skokenes/D3-Lasso-Plugin#11]
Hey skokenes,

First off, I wanted to say that this is a great widget. As someone with very little d3 knowledge, this gave me a nice entry point.

I did notice, however, that not every lasso selection included all of the points in the selection. It might be a problem specific to non-convex selection areas, but I'm not 100% sure.

Thanks,

![lasso_sel_bug](https://cloud.githubusercontent.com/assets/8890017/15219470/ebbfd7f0-1831-11e6-9c1e-2f90284a2292.png)

**Comment by ghost** [comment]
+1 Same here

**Comment by skokenes** [comment]
Can you show some examples, maybe via animated GIF, of the shape that you
are drawing to produce these results? That way I can reproduce. Thanks!

**Comment by ghost** [comment]
Here's a screenshot of one example:

![Example](http://i.imgur.com/MUSao9I.png)

And a video of another example. You can see it takes a couple of attempts to get one that fails, but even the earlier ones flicker at the end.

[![Video](https://img.youtube.com/vi/mvZtAhz8ju0/0.jpg)](https://www.youtube.com/watch?v=mvZtAhz8ju0)

**Comment by ghost** [comment]
Here's another video that shows something interesting and should be easily reproduce-able.

It shows that each of the four data points flickers (becomes unselected and selected) when the y coordinate of the cursor is exactly on the y position of the data point. It might have something to do with the reported issue.

[![Video](https://img.youtube.com/vi/STQ8AzyRUcg/0.jpg)](https://www.youtube.com/watch?v=STQ8AzyRUcg)

**Comment by projecttiles** [comment]
Thanks Baz! I was going to show similar example, but the computer I'm on
right now is on its last legs (slows easily during screengrabs).

I can't find any issue that's directly attributable in your code, but it's
likely within the lasso draw method.

**Comment by projecttiles** [comment]
Hey skokenes,
has there been any update to this? How can we help fix the issue with you?

Thanks,

-PT

**Comment by projecttiles** [comment]
I think this block:
                       if(d.lassoPoint.cy === cur_pos_obj.y && d.lassoPoint.cy != prior_pos_obj.y) {
                        last_known_point = {
                            x: prior_pos_obj.x,
                            y: prior_pos_obj.y
                        };
on lines 186-194 in lasso.js is the root of the problem. WACMemphis mentioned a flickering whenever the y-value of a point was crossed causing deselection.

I hope this helps! I wish I knew js better myself so that I could be of more help.

-PT

**Comment by ghost** [comment]
@skokenes Any update on this? I've tried to fix it myself, but can't seem to be able to.

**Comment by projecttiles** [comment]
He opened up a new empty repo because he wanted to add d3 v4 support. However, I have no clue what to expect from that or when. 

This is so close to ideal. I've been spending all of my time in Python, so web dev and js are still quite foreign to me.

**Comment by skokenes** [comment]
Hi, I've migrated the library to v4 with some better code under the hood. Can you please test out that version?

There has been little interest from the community in helping maintain the d3 v3 version of this plugin, so I may close this repo and focus sole on the new repo going forward

https://github.com/skokenes/d3-lasso
