### ISSUE TITLE
Subsequent selections dont work

### ISSUE THREAD

**Issue by nite** [skokenes/D3-Lasso-Plugin#4]
In your scatterplot example, subsequent selections (after the first) are a little flaky - they dont stop completely, but only occasionally work. Might also be worth keeping the lasso in place until de-selection!

**Comment by nite** [comment]
Didnt notice you need to close the loop, ie. make sure cursor is near the start - this may require a little training, so would be good to have it always close!

**Comment by skokenes** [comment]
There is a parameter that controls how close you need to be to close the
loop. If you want it to always close, you can just set this parameter
arbitrarily high, like

lasso._closePathDistance_(_10000_)

**Comment by nite** [comment]
great, thanks!
