### ISSUE TITLE
scale function for x, y axis.

### ISSUE THREAD

**Issue by ajing** [skokenes/D3-Lasso-Plugin#5]
D3 brush has a function to attach xscale, yscale function: brush.x().y(). I want to change Lasso's source code to support this function. However, I am not quit sure which line I should change. Is there any easy way to do that? I was trying to just change dragstart(), 

``` javascript
d.lassoPoint = {
    cx: x(Math.round(new_box.left-offset_box.left + new_box.width/2)),
    cy: y(Math.round(new_box.top-offset_box.top + new_box.height/2)),
    edges: {top:0,right:0,bottom:0,left:0},
    close_edges: {left: 0, right: 0}
};
```

but it doesn't work.

**Comment by skokenes** [comment]
Can you file this issue under v4 and provide an example where it would be beneficial to use a scale like this? Right now, the lasso calculates point locations based on their position in the DOM

https://github.com/skokenes/d3-lasso
