### ISSUE TITLE
Radial Tree issue

### ISSUE THREAD

**Issue by countnazgul** [skokenes/D3-Lasso-Plugin#6]
I'm trying to use the lasso plugin with radial tree chart ( http://bl.ocks.org/mbostock/4063550 ) but somehow cant make it to work. 
I can draw the lasso area and the lasso itself is there but the selection dont work as expected - selecting small area dont select anything, selecting bigger area select all the dots. 
Is it possible to tell me where im going wrong?

here is an example of what ive done so far: http://codepen.io/anon/pen/ZbBPxd

Thanks
Stefan

**Comment by skokenes** [comment]
Hi, I've migrated the library to v4 with some better code under the hood. Can you please test out that version?

There has been little interest from the community in helping maintain the d3 v3 version of this plugin, so I may close this repo and focus sole on the new repo going forward

https://github.com/skokenes/d3-lasso
