### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ngopal** [skokenes/D3-Lasso-Plugin#7]
Hi. Really cool plugin! I was going to write a lasso function for a prototype app for my PhD project. However, I'm inclined to just use yours if you are okay with that.

Are you planning on assigning a license on this code soon?

**Comment by ghost** [comment]
+1 I'm interested in license information as well.

**Comment by skokenes** [comment]
You're free to use it, I will assign an open license

**Comment by skokenes** [comment]
License has been added
