### ISSUE TITLE
Scatter Matrix with Lasso

### ISSUE THREAD

**Issue by ghost** [skokenes/D3-Lasso-Plugin#8]
I love this plugin and I'm using it extensively now. It's working perfect when using it with a simple scatter plot.

I've not tried to get it working with the Scatterplot Matrix example that can be found here: http://bl.ocks.org/mbostock/4063663

I basically want to replace the brushing with the lasso, but I can't get it to work. Does anyone have any ideas?

**Comment by whatwehaveunlearned** [comment]
What problem are you having?

**Comment by ghost** [comment]
I can get it to draw the lasso, but no points are selected. Not sure if I'm doing it right.

**Comment by skokenes** [comment]
Can you post a gist with sample code?

**Comment by ghost** [comment]
https://jsfiddle.net/nhgkhkwd/

Hope this helps. It does set all circles to "not_possible", but it doesn't select any of them, i.e. d.possible is always false.

**Comment by skokenes** [comment]
Hi, I've migrated the library to v4 with some better code under the hood. Can you please test out that version?

There has been little interest from the community in helping maintain the d3 v3 version of this plugin, so I may close this repo and focus sole on the new repo going forward

https://github.com/skokenes/d3-lasso
