### ISSUE TITLE
close_path_node is not defined 

### ISSUE THREAD

**Issue by NoobSkywalker** [skokenes/D3-Lasso-Plugin#9]
Ill get an error for close_path_node is not defined and i kinda dont get why, was this a bug in an old version ? or do you have any ideas what can cause this issue ?

**Comment by NoobSkywalker** [comment]
was a problem with the old version used in d3-plugins-dist

**Comment by simondachstr** [comment]
Can you please elaborate a bit more on how you fixed the error?

**Comment by NoobSkywalker** [comment]
well actually this is already almost half a year ago. Sorry but i can't
really tell anymore what the problem was :-)

2016-07-20 13:04 GMT+02:00 simondachstr notifications@github.com:
